### ISSUE TITLE
fix pending bets sync they're crashing on when there is there is a failed transaction

### ISSUE THREAD

**Issue by janfilips** [janfilips/blockchain-dice#89]

**Comment by jparicka** [comment]
this could be regularly failed transaction

**Comment by jparicka** [comment]
tx_hash 0xd58a23ca288e458d537e3fea9a8a839f83bb612a827400cd1f92ceec7267c2bc
callback_tx_hash 
Traceback (most recent call last):
  File "robot_fix_pending_bets.py", line 62, in <module>
    decoded_tx = contract.decode_function_input(event_tx.input)
AttributeError: 'NoneType' object has no attribute 'input'

it's this error....

**Comment by jparicka** [comment]
https://etherscan.io/tx/0xd58a23ca288e458d537e3fea9a8a839f83bb612a827400cd1f92ceec7267c2bc

**Comment by mindfulme** [comment]
got it

**Comment by janfilips** [comment]
thank you big sir but the project is long dead I'm afraid
I used to run it here http://18.157.182.120:8003/
:P
